FROM php:8.1.6-fpm-alpine

RUN apk update && apk upgrade

RUN docker-php-ext-install opcache pdo pdo_mysql mysqli
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
